# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            <p style="font-size: 20px">Geography, equity, and the Seattle $15 minimum wage ordinance</p>
tagline:          ''
description:      'A Data Science for Social Good 2021 fellowship project.'
url:              "https://uwescience.github.io"
baseurl:          "/MinWA"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/uwescience/MinWA/
