# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            'Seattle $15 Minimum Wage Project'
tagline:          ''
description:      'A Data Science for Social Good 2021 fellowship project.'
url:              "https://uwescience.github.io"
baseurl:          "/MinWA"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/uwescience/MinWA/
