# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            <font size="20"> Geography, equity, and the Seattle $15 minimum wage ordinance</font>
tagline:          'Seattle Minimum Wage Study'
description:      'A Data Science for Social Good 2021 fellowship project.'
url:              "https://uwescience.github.io"
baseurl:          "/MinWA"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/uwescience/MinWA/
