# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            Geography, equity, and the Seattle $15 minimum wage ordinance
tagline:          ''
description:      'project examines the minimum wage as a solution to income inequality – and one potential limitation to this approach. In 2014, Seattle was the first major city to pass a $15 minimum wage. Policymakers hoped that higher wages for low-paid workers would reduce inequality and poverty and make Seattle workers and their families better off. However, the phase-in of Seattle’s $15 wage coincided with another economic jolt– the rapid influx of tens of thousands of high-paid technology workers. These new arrivals needed housing. Rental prices climbed rapidly, and large swaths of the city quickly gentrified. As a result, low-wage workers were likely priced out of Seattle housing just as the raise to $15 took effect. While economists argue over the extent to which increasing minimum wages lowers *demand* for low-paid workers, our hot housing market might have also affected the *supply* of people looking for low-paid jobs. This project will probe the hypothesis that the supply of low-wage labor dropped in Seattle over the years 2014-2016. Our DSSG team will work to understand residential relocation (moves) relative to places of employment (jobs) in the Puget Sound.'
url:              "https://uwescience.github.io"
baseurl:          "/DSSG-website-template"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/uwescience/DSSG-website-template/
