# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            'Seattle Min Wage'
tagline:          ''
description:      'Geography, equity, and the Seattle $15 minimum wage ordinance'
url:              "https://uwescience.github.io"
baseurl:          "/DSSG-website-template"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/uwescience/DSSG-website-template/
